import { Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { Exam, Prisma, ExamAttempt, AttemptStatus } from '@prisma/client';

@Injectable()
export class ExamsService {
  constructor(private prisma: PrismaService) {}

  async findAll() {
    return this.prisma.exam.findMany({
      include: { instructor: { select: { name: true } } },
    });
  }

  async findOne(id: string) {
    const exam = await this.prisma.exam.findUnique({
      where: { id },
      include: { questions: true },
    });
    if (!exam) throw new NotFoundException('Exam not found');
    return exam;
  }

  async create(data: Prisma.ExamCreateInput) {
    return this.prisma.exam.create({ data });
  }

  async update(id: string, data: Prisma.ExamUpdateInput) {
    return this.prisma.exam.update({ where: { id }, data });
  }

  async delete(id: string) {
    return this.prisma.exam.delete({ where: { id } });
  }

  async startAttempt(userId: string, examId: string) {
    return this.prisma.examAttempt.create({
      data: {
        userId,
        examId,
        status: 'STARTED',
      },
    });
  }

  async submitAttempt(attemptId: string, answers: { questionId: string; response: string }[]) {
    const attempt = await this.prisma.examAttempt.findUnique({
      where: { id: attemptId },
      include: { exam: { include: { questions: true } } },
    });

    if (!attempt) throw new NotFoundException('Attempt not found');
    if (attempt.status === AttemptStatus.SUBMITTED) return attempt;

    let score = 0;
    const studentAnswersData = [];

    for (const answer of answers) {
      const question = attempt.exam.questions.find((q) => q.id === answer.questionId);
      if (!question) continue;

      let pointsEarned = 0;
      if (question.type === 'MCQ' || question.type === 'TRUE_FALSE') {
        if (question.answer === answer.response) {
          pointsEarned = question.points;
        }
      }
      
      score += pointsEarned;
      studentAnswersData.push({
        questionId: question.id,
        response: answer.response,
        pointsEarned,
      });
    }

    return this.prisma.examAttempt.update({
      where: { id: attemptId },
      data: {
        score,
        status: AttemptStatus.SUBMITTED,
        submitTime: new Date(),
        answers: {
          createMany: {
            data: studentAnswersData,
          },
        },
      },
    });
  }

  async generateResultPdf(attemptId: string, res: any) {
    const PDFDocument = require('pdfkit');
    const attempt = await this.prisma.examAttempt.findUnique({
      where: { id: attemptId },
      include: {
        exam: true,
        user: true,
      },
    });

    if (!attempt) throw new Error('Attempt not found');

    const doc = new PDFDocument();
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=result-${attemptId}.pdf`);
    doc.pipe(res);

    doc.fontSize(25).text('OFFICIAL EXAM RESULT', { align: 'center' });
    doc.moveDown();
    doc.fontSize(16).text(`Exam: ${attempt.exam.title}`);
    doc.text(`Candidate: ${attempt.user.name}`);
    doc.text(`Score: ${attempt.score}%`);
    doc.text(`Status: ${attempt.status}`);
    doc.text(`Completion Date: ${new Date().toLocaleDateString()}`);
    
    doc.moveDown();
    doc.fontSize(12).text('Generated by OEMS System', { align: 'center', oblique: true });
    doc.end();
  }

  async getResults(userId: string) {
    return this.prisma.examAttempt.findMany({
      where: { userId, status: AttemptStatus.SUBMITTED },
      include: { exam: true },
      orderBy: { submitTime: 'desc' },
    });
  }

  async getStudentStats(userId: string) {
    const attempts = await this.prisma.examAttempt.findMany({
      where: { userId, status: AttemptStatus.SUBMITTED },
      include: { exam: true },
    });

    const totalExams = attempts.length;
    const averageScore = totalExams > 0 
      ? attempts.reduce((acc, curr) => acc + curr.score, 0) / totalExams 
      : 0;
    
    // Simple mock for "Hours Spent" based on exam durations
    const totalMinutes = attempts.reduce((acc, curr) => acc + curr.exam.duration, 0);
    const hoursSpent = Math.floor(totalMinutes / 60);

    return {
      totalExams,
      completedExams: totalExams,
      averageScore: Math.round(averageScore),
      hoursSpent: `${hoursSpent}h`,
      recentAttempts: attempts.slice(0, 3).map(a => ({
        id: a.id,
        examTitle: a.exam.title,
        score: a.score,
        date: a.submitTime,
      })),
    };
  }

  async getAttemptDetails(attemptId: string) {
    const attempt = await this.prisma.examAttempt.findUnique({
      where: { id: attemptId },
      include: {
        exam: {
          include: {
            questions: true,
          },
        },
        answers: true,
      },
    });

    if (!attempt) throw new NotFoundException('Attempt not found');
    return attempt;
  }
}
